# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false
contact_links:
- name: 'âœï¸ Poetry Issue Tracker'
  url: https://github.com/python-poetry/poetry/issues/new/choose
  about: |
    Submit your issues to the Poetry issue tracker. Bug reports and feature requests
    will be tracked there.
- name: 'ğŸ’¬ Discord Server'
  url: https://discordapp.com/invite/awxPgve
  about: |
    Chat with the community, ask questions and learn about best practices.
